name: Execute Logging

on:
  push:
    branches:
      - main
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Ejecutar script
        run: |
          python log.py
