name: Weekly Security Scan

on:
  schedule:
    - cron: '0 3 * * 1' # Cada Lunes a las 03.00 UTC
  workflow_dispatch: # Para poder ejecutar cuando queramos desde Github Actions, así no hace falta esperar a cuando 'le toca' ejecutarse

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run audit
        run: pip-audit
